# AWS
BUCKET_NAME = "032854191254-patate"
ENV_VAR_FOR_AWS_USER_ID = "PATATE_S3_KEY_ID"
ENV_VAR_FOR_AWS_USER_KEY = "PATATE_S3_KEY"

# ES cluster
ES_HOST_IP = "patate-db.com/elastic"
ES_HOST_PORT = 9200
ES_INDEX = "patate-db"
ENV_VAR_FOR_ES_USER_ID = "PATATE_ES_USER_ID"
ENV_VAR_FOR_ES_USER_KEY = "PATATE_ES_USER_PWD"
