# Car max value
MAX_SPEED = 307
STOP_SPEED = 322
MAX_DIRECTION_LEFT = 1
MAX_DIRECTION_RIGHT = 651

# MAPPING
_LINEAR = []
_FIVE_DIRECTION = [250, 290, 327, 364, 400]
_TWO_DIRECTION = [250, 327, 400]
_FIVE_JOYSTICK_POS = [-0.8, -0.1, 0.1, 0.8]
_TWO_SPEED = [318, 318]
_TWO_TRIGGER_POS = [0.8]
STOP_SPEED_LABEL = -1

# TRAINING MAPPING
JOYSTICK_TO_RAW_DIR_MAPPING = _LINEAR
TRIGGER_TO_RAW_SPEED_MAPPING = _LINEAR

# LABELIZATION MAPPING
RAW_DIR_TO_LABEL_MAPPING = _FIVE_DIRECTION
RAW_SPEED_TO_LABEL_MAPPING = _TWO_SPEED

# RACE MAPPING
LABEL_TO_RAW_DIR_MAPPING = _FIVE_DIRECTION
LABEL_TO_RAW_SPEED_MAPPING = _TWO_SPEED


# 2 directions head
HEAD_UP = 120
HEAD_DOWN = 120

# Camera Settings
IMAGE_SIZE = (160, 96)  # why ?
FRAME_RATE = 32
EXPOSURE_MODE = "off"
