from conf import mappings

# Car max value
MAX_SPEED = 307
STOP_SPEED = 322
MAX_DIRECTION_LEFT = 1
MAX_DIRECTION_RIGHT = 651

# Motor speed
SPEED_NORMAL = 316  # top speed 314
SPEED_FAST = 311  # top speed 307

# 5 directions wheels
DIRECTION_L_M = 250
DIRECTION_L = 290
DIRECTION_C = 327
DIRECTION_R = 364
DIRECTION_R_M = 400

# MAPPING
_LINEAR = []
_FIVE_DIRECTION = [250, 290, 327, 364, 400]
_TWO_DIRECTION = [250, 327, 400]
_FIVE_JOYSTICK_POS = [-0.8, -0.1, 0.1, 0.8]
_TWO_SPEED = [316, 311]
_TWO_TRIGGER_POS = [0.8]

# TRAINING MAPPING
JOYSTICK_TO_RAW_DIR_MAPPING = _LINEAR
RAW_DIR_TO_LABEL_MAPPING = _FIVE_DIRECTION
TRIGGER_TO_RAW_SPEED_MAPPING = _LINEAR
RAW_SPEED_TO_LABEL_MAPPING = _TWO_SPEED

# RACE MAPPING
LABEL_TO_RAW_DIR_MAPPING = _FIVE_DIRECTION
LABEL_TO_RAW_SPEED_MAPPING = _TWO_SPEED


# 2 directions head
HEAD_UP = 150
HEAD_DOWN = 120

# Camera Settings
IMAGE_SIZE = (160, 96)  # why ?
FRAME_RATE = 32
EXPOSURE_MODE = "off"
