# Generated by Django 2.2.7 on 2020-02-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_auto_20200208_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='to_delete',
            field=models.BooleanField(default=False),
        ),
    ]
