# Generated by Django 2.2.7 on 2020-02-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_photo_to_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
